### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by ashkan957** [Drakkar-Software/Triangular-Arbitrage#12]
Hello, I did the installation procedure successfully as instructed; 

However, when I started the project using "python main.py" command ("pyhton3" was not acceptable), it gave me this error: 

Scanning...
0it [00:00, ?it/s]
-------------------------------------------
New 0% bitget opportunity:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Triangular-Arbitrage_1.0.4\main.py", line 28, in <module>
    print(f"{i+1}. {get_order_side(best_opportunities[i])} {str(best_opportunities[i].symbol)}")
                                   ~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable


What should I do to solve this error? Are the API addresses up-to-date?

I appreciate your assistance to solve this issue.
Thanks.
Sincerely

**Comment by Herklos** [comment]
Can you please retry with the latest version?
